version: '2'
exclude_paths:
  - 'resources'
  - 'www'
  - '**/*.log'
  - '**/*.ico'
  - 'e2e/'
  - 'src/assets/'
  - 'src/typings.d.ts'
  - 'src/app/**/*.spec.ts'
  - 'ionic.config.json'
  - 'ionic.starter.json'
  - 'package.json'
  - 'package-lock.json'
