dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

addons:
  code_climate:
    repo_token: b5393f5ae154b9eb52fedf6164a17868fd27e7ec1713c0dd93d7876f3cf07255

branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/

cache:
  directories:
    - ./node_modules

before_install:
  - npm install -g ionic cordova

install:
  - pushd $TRAVIS_BUILD_DIR
  - npm install

script:
  - npm run test-coverage
  - ionic cordova build browser --prod

after_script:
  - coverage

notifications:
  email:
    recipients:
      - rajeyw@gmail.com
    on_failure: always
    on_success: always
