dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

addons:
  apt:
    packages:
      - openjdk-8-jdk

jdk: openjdk8

branches:
  only:
    - master
    - develop

cache:
  directories:
    - ./node_modules

before_install:
  - curl -s "https://get.sdkman.io" | bash
  - sdk install gradle 5.4
  - npm install -g ionic cordova

install:
  - pushd $TRAVIS_BUILD_DIR
  - npm install

script:
  - ionic cordova build android --prod

notifications:
  email:
    recipients:
      - rajeyw@gmail.com
    on_failure: always
    on_success: always
